# Generated by Django 6.0 on 2025-12-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains', 'Grains & Pulses'), ('dairy', 'Dairy & Eggs')], default='vegetables', max_length=20),
        ),
    ]
