# Generated by Django 6.0 on 2026-01-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_app', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains', 'Grains & Pulses')], default='vegetables', max_length=20),
        ),
    ]
