# Generated by Django 6.0 on 2026-01-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Check this to show on Home Page Featured section'),
        ),
    ]
