# Generated by Django 6.0 on 2025-12-27 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('VegetableName', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('District', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('Id_proof', models.CharField(max_length=50)),
                ('Id_number', models.CharField(max_length=50)),
                ('Profile_photo', models.ImageField(blank=True, null=True, upload_to='farmers/profiles/')),
                ('Is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
