# Generated by Django 6.0 on 2026-01-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_updated',
            field=models.BooleanField(default=False),
        ),
    ]
