# Generated by Django 6.0 on 2025-12-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
